# This is a basic workflow to help you get started with Actions

name: Publish CI

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-chrome-extension:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    defaults:
      run:
        working-directory: tc/chrome/plugins
    outputs:
      VERSION: ${{ steps.version-string.outputs.VERSION }}

    steps:
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Build
        run: |-
          # fill in your build steps here...
          # we archive the dist folder and include SHA commit as the last step
          mkdir tcCrExtension
          cp *.js *.htm tcCrExtension
          #zip -r chrome-extension-${{ github.event.pull_request.head.sha }}.zip tcCrExtension
          zip -r tcCrExtension.zip tcCrExtension
          
      - name: Archive chrome-extension artifact
        uses: actions/upload-artifact@v3
        with:
          name: tcCrExtension
          path: tc/chrome/plugins/tcCrExtension.zip


